#
# https://github.com/cuiyf5516/Actions-OpenWrt
#
# File: .github/workflows/build-amd64-openwrt.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
# Copyright (c) 2021-2026 cuiyf5516 <yjcuiyf@gmail.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build AMD64 OpenWrt

concurrency:
  group: build-amd64-openwrt-${{ github.ref }}
  cancel-in-progress: true

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 14 * * 5 
      timezone: Asia/Shanghai 

jobs:
  build:
    uses: ./.github/workflows/_build-openwrt-reusable.yml
    with:
      config_file: config/amd64.config
      cache_mixkey: amd64
      release_prefix: AMD64
    secrets: inherit
