#
# https://github.com/cuiyf5516/Actions-OpenWrt
#
# File: .github/workflows/build-r2s-openwrt.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
# Copyright (c) 2021-2026 cuiyf5516 <yjcuiyf@gmail.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build R2S OpenWrt

concurrency:
  group: build-r2s-openwrt-${{ github.ref }}
  cancel-in-progress: true

on:
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 0 14 * * 5
#      timezone: Asia/Shanghai

jobs:
  build:
    uses: ./.github/workflows/_build-openwrt-reusable.yml
    with:
      config_file: config/r2s.config
      cache_mixkey: aarch64
      release_prefix: R2S
    secrets: inherit
