#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build AMD64 OpenWrt

concurrency:
  group: build-amd64-openwrt-${{ github.ref }}
  cancel-in-progress: true

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  schedule:
    - cron: 0 14 * * 5 
      timezone: Asia/Shanghai 

jobs:
  build:
    uses: ./.github/workflows/_build-openwrt-reusable.yml
    with:
      ssh: ${{ github.event.inputs.ssh || 'false' }}
      config_file: config/amd64.config
      cache_mixkey: amd64
      release_prefix: AMD64
    secrets: inherit
