#
# https://github.com/cuiyf5516/Actions-OpenWrt
#
# File: .github/workflows/build-r2s-openwrt.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
# Copyright (c) 2021-2026 cuiyf5516 <yjcuiyf@gmail.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build R2S OpenWrt

concurrency:
  group: build-r2s-openwrt-${{ github.ref }}
  cancel-in-progress: true

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source:
        description: Source repository
        required: true
        default: immortalwrt
        type: choice
        options:
          - immortalwrt
          - lede
#  schedule:
#    - cron: 0 14 * * 5
#      timezone: Asia/Shanghai

permissions:
  actions: write
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-openwrt-reusable.yml
    with:
      source: ${{ inputs.source || github.event.client_payload.source || 'immortalwrt' }}
      config_file: config/${{ inputs.source || github.event.client_payload.source || 'immortalwrt' }}/r2s.config
      release_prefix: R2S-${{ inputs.source || github.event.client_payload.source || 'immortalwrt' }}
    secrets: inherit
